server:
  port: 8881
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
  main:
    web-application-type: reactive
# spring:
#   cloud:
#     gateway:
# #       default-filter:
# #         -DedupeResponseHeader: Access-Control-Allow-Origin
#       globalcors:
#         corsConfigurations:
#           '[/**]':
#             allowedOrigin: "http://localhost:4201"
#             allowedMethods:
#               - GET
#               - POST
# spring:
#   main:
#     web-application-type: reactive
#     allow-bean-definition-overriding: true
#allowedOrigins: "*"
