server:
  port: 8881

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
# spring:
#   main:
#     web-application-type: reactive
#     allow-bean-definition-overriding: true
#allowedOrigins: "*"
