server:
  port: 8881

spring:
  cloud:
    gateway:
      default-filter:
        -DedupeResponseHeader: Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
# spring:
#   main:
#     web-application-type: reactive
#     allow-bean-definition-overriding: true
#allowedOrigins: "*"
