server:
  port: 8881
# spring:
#   cloud:
#     gateway:
#       default-filters:
#         - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#       globalcors:
#         corsConfigurations:
#           '[/**]':
#             allowedOrigins: "*"
#             allowCredentials: false
#             allowedHeaders: "*"
#             allowedMethods:
#               - GET
#               - POST
#               - PUT
#               - DELETE
spring:
  main:
    web-application-type: reactive
